# Generated by Django 3.0.5 on 2020-04-23 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot_init', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_spam', models.BooleanField(default=False)),
                ('sub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot_init.Subscriber')),
            ],
        ),
    ]
